### ISSUE TITLE
Question: How to handle OffsetDateTime with Elide Spring Boot

### ISSUE THREAD

**Issue by murtuza-ranapur** [yahoo/elide#1128]
I have a property in my entity with `OffsetDateTime` type, but Eldie seems to throw stackOverfow error whenever i try to start my Spring Boot Application. I assume there is no in build support for the same in Eldie  

Please suggest a way to register new GraphQL scalar type. I know about Serde from documentation, but it would be great if you could provide a way to register new ones with Eldie.

## Steps to Reproduce (for bugs)
1. Add `OffsetDateTime` in your Entity

## Your Environment
* Elide version used: 4.5.9
* Environment name and version (Java 1.8.0_152): 1.8
* Operating System and version: Windows 10

**Comment by aklish** [comment]
You will need to register a SerDe with Elide to support this type.  

Check out:
https://elide.io/pages/guide/09-clientapis.html and look at the section on "User Type Registration".

**Comment by murtuza-ranapur** [comment]
This is the brief snapshot of my entity
```
@Include(rootLevel = true, type = "sample")
@Entity
class Sample{
	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid2")
	private String id;

        private OffsetDateTime submittedDate;  <----

	@Column(name = "title", length = 100)
	private String title;

	@Column(name = "summary", length = 600)
	private String summary;

	@Column(name = "detailed_description", length = 600)
	private String detailedDescription;
        ....
}
```
When my spring project starts Elide tries to generate GraphQL schema from the Included entities. It tries to convert all types to GraphQLScalar to do so Elide uses `GraphQLConversionUtils` classes `classToScalarType` which converts `Date` or its sub-types but `OffsetDateTime` is a sub-type of `Temporal` class. Hence it returns null and code execution goes in to `classToInputObject` which leads to StackOverflow Error.

The only solution i found to my problem was to extend `GraphQLConversionUtils` and override `classToScalarType` method to support  either `OffsetDateTime` or `classToScalarType`.

Please let me know if there is an easier way to do this.

**Comment by aklish** [comment]
Sorry - It has been a while since I've looked at this code. 

You are correct that Elide is missing a good way to register a custom type for GraphQL - and you have identified the problem.

I think two fixes are in order:

1.  Elide should support a number of common data types out of the box for GraphQL - including some of the Temporal types from java.time as well as UUID and Currency I believe.  Those are all pretty common.

2. There should be a new way to register a GraphQLScalarType - as this extra bit of logic is needed to bridge the Serde logic with GraphQL parsing.

This seems to me high on the priority to fix asap so will add it to next sprint.  If you are inclined to submit any of your work for native support for OffsetDateTime, I'd be happy to look at that and get it integrated.

**Comment by murtuza-ranapur** [comment]
Sure, I would like to contribute. Currently, I have simply added one more condition for offset in the same function, but problem of extendibility still remains. I have some ideas for it. Will raise a PR soon.

**Comment by murtuza-ranapur** [comment]
Hello @aklish i have raised PR for the same. But my Travis build is failing on elide-core Style-check which i have most certainly fixed in the following commit. I am sure about it as builds have started passing on my local machine after it. I think Travis is not picking up the latest code. It would be great if could suggest something
