### ISSUE TITLE
Logger should be named AuditLogger

### ISSUE THREAD

**Issue by christianbauer** [yahoo/elide#125]
The documentation says it's called AuditLogger but the source name is Logger. Also, Logger is a really bad name for this interface.

**Comment by DeathByTape** [comment]
Good catch, we should probably rename this. At the very least, we should update the source to be consistent with the documentation. Do you have a recommendation instead of using `AuditLogger`? We should be releasing "2.0" (reworked security backend, etc.) very soon which will contain some breaking API changes, so we could work this into that release.

**Comment by DeathByTape** [comment]
btw, I have included this in the PR here: https://github.com/yahoo/elide/pull/111

I will leave this ticket open until that PR finally becomes mainline.
