### ISSUE TITLE
AsyncExecutorService possible to use in Jooby

### ISSUE THREAD

**Issue by tomsiwik** [yahoo/elide#1502]
While I'm currently happily using the Spring Boot version of Elide. I recently came across the 5x async version of it in

https://github.com/yahoo/elide/tree/5.0.0-pr15/elide-async/src/main/java/com/yahoo/elide/async/service

and was wandering if this could be integrated in a similar way like the native ExecutorServices with other server implementations, e.g:

https://jooby.io/v1/doc/executor/#executor-multiple-executors

I haven't had much time looking into it and I apologise for the direct question. If this is possible and worth investigating/investing time I would be glad to look into it if somebody could point me to the right direction. I haven't found any examples that actually use a middleware approach or the new async api with something other than spring boot or standalone (jetty).

Thanks in advance. Keep up JSON:API, GQL, OA and PatchExtensions... love them!

**Comment by aklish** [comment]
I'll have to do a bit more investigation into jooby and how it uses executors.  

I think there are two kinds of async.  I don't have good names for them, but let me define what I mean:

- **Server async** - which relates to how logic inside a container is scheduled and executed.
- **Client async** - which relates to how the client interacts with a server.

For server async, Elide 5 is leveraging Spring's async infrastructure:
https://github.com/yahoo/elide/blob/elide-5.x/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/controllers/JsonApiController.java#L65-L81

Client async is being added because we are adding _analytic_ querying capability to Elide.  Analytics have some unique client constraints:

- Queries can take minutes and sometimes even hours to run.  This means the client needs to move from a blocking model to a polling model.
- The data volume returned can be quite high and sometimes the client wants all of it (unpaginated).
- We are allowing the client control over how long it is willing to block waiting on a response.  This means our service will block for N seconds, after which the client converts to the polling model.

The reason we are bringing analytics and CRUD together into a single abstraction is because we also plan on releasing some other open source projects that will be leveraging them together.  

I hope that helps explain what is coming in elide 5.  If you think jooby's executor model is a good fit for either of these use cases, I'd definitely be interested to discuss & learn more.

**Comment by tomsiwik** [comment]
Thank you very much for the thorough explanation. That very much explains the reasoning behind async from my point of view. I'm currently looking into lightweight and highly performant solutions (Micronaut, Jooby) hence the question how this could be combined to work with something like Jooby. I haven't found a smooth way to use the 'middleware' approach yet to implement Elide in ANY framework. However I'm currently investigating Micronaut because of that (Spring Boot like Autoconfigure). Probably I'll go with the latter. Thanks again 👍
