### ISSUE TITLE
Redis data store

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#2311]
I want to make a custom store - Redis data store that will support create/update/delete operations of models but rely on Elide for filtering, sorting, or pagination.

I did look into the example of `BridgeableRedisStore` and looks like it is not the use-case that I want to implement.

Also, I definitely need your help on this. Could you please provide detailed instructions on the implementation? A skeletal implementation would be a great guidance.

**Comment by aklish** [comment]
I would check out the [HashMapDataStore](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapDataStore.java) and [HashMapDataStoreTransaction](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/HashMapStoreTransaction.java).

The transaction tells elide to do all sorting, filtering, and pagination in memory.  

I imagine a Redis data store would be very similar to the hashmap (but instead of storing values in a HashMap, they are stored in Redis).

If you get something working and want to submit it, I think it would make a good addition as a general data store.

**Comment by thaingo** [comment]
Thanks @aklish. I will probably start implementing this next weekend and need your review as always. Hope that I will not bother you too much with this :).
