### ISSUE TITLE
Question: Is it possible to implement localization (i18n) using Elide

### ISSUE THREAD

**Issue by pagexv** [yahoo/elide#2815]
Hello, 

I am trying to build a json api server that supports multi-language. And I am able to implment this using Read LifeCycle Hook. However, when I upgarde Elide to v6, the Read Hook is removed. So I am looking for some ideas of how to work around this using Elide.

## Expected Behavior

Input of Rest api call

```
curl --location -g --request GET '{{ADMIN_URI}}/resource-server' \
--header 'Content-Type: application/vnd.api+json; ext=jsonpatch' \
--header 'ApiVersion: v1.0' \
--header 'Accept-Language: <any-locale-string>'
```

Output

```
{ "name": "Output language depends on <any-locale-string>"}
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

With read hook gone, I don't have access to the EntityDictionary class. I wonder if there is a workaround for this.

## Your Environment

* Elide version used: After 6.0.0-pr6 https://github.com/yahoo/elide/pull/2381
* Environment name and version (Java 1.8.0_152):
* Operating System and version:
* Link to your project:

**Comment by aklish** [comment]
You could wrap the DataStore you leverage for Elide with a custom store that delegates to the wrapped store for all calls but does the localization lookup for attributes.

The only method you need to implement (rather than delegate) in the store is the method that creates transactions:
https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStore.java#L27

This method returns a custom transaction that you create that wraps another transaction.  There is a handy class for this:
https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/wrapped/TransactionWrapper.java

Your custom transaction which extends the above wrapper only needs to override: 

https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/datastore/DataStoreTransaction.java#L258
 
That's where your localization logic would live.

To register your custom store with Elide, you can override this bean in spring boot:

https://github.com/yahoo/elide/blob/master/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java#L406-L446

I hope that makes sense.  If you go this route and have questions, let me know.

**Comment by pagexv** [comment]
Thanks for your response, it really helps
