### ISSUE TITLE
How to include "links" attribute in response?

### ISSUE THREAD

**Issue by bduisenov** [yahoo/elide#282]
I was not able to find any example.

**Comment by clayreimann** [comment]
I don't think we support `links` at the moment. @DeathByTape might know differently

**Comment by bduisenov** [comment]
Hi @clayreimann @DeathByTape, I can create PR with this. I was able to supplement Elide responses with "self" & "related" links. But I'm not sure whether initial url path should set with Elide.Builder or somehow differently.

**Comment by DeathByTape** [comment]
I believe the links can be relative. While I can't find any explicit mention of this in the jsonapi spec, [they do have an example](http://jsonapi.org/format/#document-resource-objects) using relative URIs. In this case, a prefix uri would be unnecessary unless you were redirecting to another service. 

What do you guys think? I feel like using relative links probably avoids the problem of having to specify your service's root prefix. It's also possible we can support both, but perhaps unnecessary.

**Comment by jimirocks** [comment]
Hello @DennisMcWherter , what is the status of links in Elide's JSON:API now? Seems like this effort didn't reach the finalization? Would you consider to finish it?

**Comment by aklish** [comment]
I think the existing approach from @bduisenov looks pretty solid.  I think some things that would be nice to add:
1. The way the lineage is stored in the PersistentResource in a map is not ideal.  Ideally, the lineage is just an ordered list of resources.  I think we could update the lineage to include this structure as well and use it instead of the map keys.
2. As referenced, it would be nice to tie this into elide-spring-boot and elide-standalone with configuration that pulls in the URL.
3. I think we should have an option to turn this off/on in settings as links inflates the payload response.  By default, it should be off.

For merging this to master, the only absolute must have on my list is 3.  The other two could be done in another PR (or together).

**Comment by rehab-reda0** [comment]
That will be great. we need links but we need also to customize it 
I mean the links object instead of containing {self; " " ,related:" "}
w may need it to contain {self: " ", name1: " ", name2:" "} is that will be applicable by this pull request ?
