### ISSUE TITLE
What's the point of customizer?

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#3271]
How builder, as an established pattern, is used in Elide is perfectly understandable. What, however, would a _customizer_ add that a regular _builder_ cannot do? For example, `ElideSettingsBuilder` v.s `ElideSettingsBuilderCustomizer`

Thanks

**Comment by justin-tay** [comment]
The customizers allow you to customize defaults. Also different parts of the application can contribute a customizer. For instance you could develop your own library with its own autoconfiguration that contributes a customizer with a low order/priority for instance that does some configuration which you might feel should be a default.

If you just create a builder then it is expected that you fully configure it yourself, which may be exactly what you want which is why the default configuration backs off if you define your own builder, but typically it usually results in a lot of copy and paste of the defaults with the added changes.

If you look at the code below you can see that the customizers are just applied to the builder after defaults are configured.

https://github.com/yahoo/elide/blob/8643a2f22021ae35534755ca1753c4537ad6cde0/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java#L213-L238

**Comment by QubitPi** [comment]
Thank you very much, @justin-tay , for the prompt reply. It sounds like we could simply start Elide with all-defaults without verbose builders and make exceptions using customizers. I think that addresses my concern. I will start with your advice and explore it further on my side

Thanks
