### ISSUE TITLE
Enabling Async API causes loss of entities' classes

### ISSUE THREAD

**Issue by HassanAzzam** [yahoo/elide#3283]
## Expected Behavior
Enabling Async API should be as easy as adding 
```yaml
  async:
    enabled: true
```
to my properties file(YAML version).

## Current Behavior
With every request to the server, I get 
```text
 java.lang.IllegalArgumentException: Not an entity: class com.xxxx.xxxx.User
```
exception.

## Possible Solution
Personally, I'm suspecting the cause of this is this line https://github.com/yahoo/elide/blob/46cd29d5ccaca3016d4bc2377e98076c25eb9b03/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java#L65

## Your Environment
* Elide version used: 7.1.1
* Environment name and version (Java 1.8.0_152): openjdk 17.0.9 2023-10-17
* Operating System and version: MacOS 10.15
* Spring boot: 3.2.5

**Comment by justin-tay** [comment]
Thanks for the bug report. You are correct that `@EntityScan` shouldn't have been used in this case.

This wasn't noticed because the `elide-spring-boot-example` has `@EntityScan` on `App`. Fixing this will possibly be a breaking change for existing users who specified `@EntityScan` as they now need to explicitly specify `AsyncQuery.class`.

**Comment by HassanAzzam** [comment]
Thank you in advance!

I did annotate my application class with `@EntityScan` and it worked as expected as a workaround for the mean time.
