### ISSUE TITLE
Are native queries supported?

### ISSUE THREAD

**Issue by micheljung** [yahoo/elide#390]
I have a use case I don't seem to be able to solve without native queries; A leaderboard for players.

Each entry needs to have a "rank", and I don't know how to do this better than sorting by score and enumerating the rows. Too bad MySQL doesn't support rownum(). I thought I'm smart and I create a view that uses the incrementing-variable-workaround, too bad MySQL doesn't support variables in views.

Having a computed value for each entry `select count(*) from players where score > myScore` could potentially work but would have massive performance issue.

I would be able to solve this issue if Elide supported some sort of native queries, but I also understand that this may not be very easy.

Any ideas or workarounds? All I think I needed is a way to specify a projection instead of a table or so :) (maybe a named query for `select * from xyz`?)

**Comment by clayreimann** [comment]
I don't understand what sort of native query you would run to lighten your DB load. (And why couldn't you run a native query like that inside your `@ComputedAttribute`?)

You could also store the player's current rank in your data model and have a background job that runs (say every hour) through and updates the player's current rank.

**Comment by aklish** [comment]
I haven't tried this, but I'm wondering if something might be possible with the following elements:

1. Named native queries in Hibernate:
https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#annotations-jpa-namednativequeries

2. SqlResultSetMapping to map the native query to your bean during loads:
https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#sql-composite-key-entity-associations_named-query-example

3. Using a variable in mysql to count the rows (something like http://stackoverflow.com/questions/3333665/rank-function-in-mysql)

If this approach works, please share.

**Comment by micheljung** [comment]
@clayreimann this query:
```
SELECT
  id,
  username,
  score,
  @s := @s + 1 rank
FROM users, (SELECT @s := 0) AS s
ORDER BY score DESC;
```
Runs in O(n). How could I achieve the same with `@ComputedAttribute`? If an `EntityListener` would know the ranks, it could easily add them, but I don't know how I would achieve that. Counting the number of players "above" each entry runs in O(n*n/2), way to expensive.

@aklish I tried named queries, but Elide doesn't seem to pick those up (which makes sense I guess?), so 1 & 2 won't work, and 3, well, see my original post ;)

**Comment by DeathByTape** [comment]
@micheljung we should look into this. I don't see a fundamental reason why Elide wouldn't support named queries since it ends up just calling directly into hibernate in the end (or using its proxy objects). I should have a chance to test this soon, but I believe this _should_ work.

I know we've tried this with hibernate3 but there are some known issues there. With hibernate5, however, if we are seeing issues there is something on our end we may need to resolve.

**Comment by aklish** [comment]
@micheljung 
I have a solution that works but you might consider waiting a few days for Elide 3.0 to be released.  Elide 3.0 is a big refactor/cleanup on the data store/transaction interfaces.

Basically, here are the steps:

(1) You would subclass HibernateStore and HibernateTransaction - maybe call them MysqlStore and MysqlTransaction.

(2) MysqlStore just needs to build a MysqlTransaction

(3) MysqlTransaction can add the following queries immediately prior to a DB fetch (In functions loadObjects and getRelation):
```
        SQLQuery query = session.createSQLQuery("set @rownum\\:=0");
        query.executeUpdate();
        query = session.createSQLQuery("set @pagenum\\:="+pagination.get().getOffset());
        query.executeUpdate();
```
This sets up variables in each query that can be used inside your bean.

(4) You can then reference those variables in a bean:
```
    @Formula("@rownum := @rownum + 1")
    public int getRank() {
        return rank;
    }
```

I tested this with a hacked up HibernateTransaction.  Since this solution is mysql specific (it involves user session variables), I'm not sure it makes sense to have a general solution as part of Elide.   However, I could be convinced otherwise.

If you want to go down this road, let me know if you have questions how to set this up.

**Comment by micheljung** [comment]
Thank you @aklish for coming back with this solution to me. Is that the pre-3.0 solution? If so, how would it work with 3.0, named queries?

For now, I solved it with a native query and a controller outside Elide, that manually builds a JSONDocument.

**Comment by aklish** [comment]
The solution would work the same way for pre-3.0 and 3.0.   I was mistaken about named queries.  Elide's hibernate store constructs queries either through Criteria or HQL.  It is not really possible to combine that construction with a native query.   However, it is possible to add snippets of native SQL through variable setting inside the data store and/or using @Formula to craft a projection using those variables.  

All that is left prior to releasing Elide 3.0 is documentation which is underway.
