### ISSUE TITLE
are sorting and filtering disabled by default ?

### ISSUE THREAD

**Issue by fabrice-etanchaud** [yahoo/elide#405]
Hello,
Are sorting and filtering disabled by default ?
Both do not work in my tests (based from your elide-persistence-mysql-example).
Is there any extra configuration to do in ElideResourceConfig ?

Thank you for your great piece of software !

Best,
Fabrice

**Comment by DeathByTape** [comment]
Oh, this is probably a fail on our end. Generally speaking, in hibernate5's [hibernate-store](https://github.com/yahoo/elide/blob/master/elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java#L210) this is properly implemented but in the [persistence store](https://github.com/yahoo/elide/blob/master/elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/PersistenceTransaction.java) it's not fully fleshed out. The persistence store preceded the hibernate store and I'm not sure anything other than this example is actually using it :)

The action item for us here is to update the persistence-store. @wcekan do we need to keep this store around for some reason? I thought you had a reason on why this would be a good idea for some users over the hibernate-store. 

We've been pretty heads down coding in preparing our elide 3.0 release and we're working on documentation now :) so we can probably add this to our list of things to fix before release (hopefully within the next few days).

In any case, a short-term solution would be if you can use the `HibernateStore` instead of `PersistenceStore`, you should get the full feature set.

**Comment by fabrice-etanchaud** [comment]
Great, now everything is working fine.
Thanks again
keep on the good job !
