### ISSUE TITLE
Does Elide support MongoDB?

### ISSUE THREAD

**Issue by MikeSuiter** [yahoo/elide#417]
I am testing out different hypermedia frameworks and for my POC I'm using MongoDB for persistence. I have a few questions:

1. Does Elide support MongoDB documents or only JPA entities? I haven't bee able to find any information on this. 
2. Is it possible to have more control over Elide using a Spring MVC RestController or something like that? 
3. Does Elide support CORS OPTIONS requests?

**Comment by DeathByTape** [comment]
1. We do not have any support for an explicit MongoDB store at the current time. However, we do support Hibernate versions 3 and 5, so if you can make it work, it may be worth investigating [Hibernate OGM](http://hibernate.org/ogm/) (which I believe supports MongoDB). I am unaware of anyone using OGM currently, but we're curious to see if it works out of box. There is no fundamental reason Elide could not support MongoDB directly at this point (and we have had some discussions about supporting this in the future), but we simply have not gotten to it yet.

2. I am confused what you're trying to accomplish. You can use an `@RestController` and it would not have any conflicts with Elide. Similarly, though somewhat dated now, there are a few tutorials (linked in the README) that describe how to use Elide with technologies such as Spring Boot. It should be noted that Elide itself can be "mounted" at any particular location you wish within a webservice. Our [examples](https://github.com/yahoo/elide/blob/elide-3.0-wip/elide-example/elide-blog-example/src/main/java/com/yahoo/elide/example) (note that is a link to the Elide 3.0 example page which should be released within a few days) typically use jetty as the webserver and manage our endpoints using Jersey. If you look at [Main.java](https://github.com/yahoo/elide/blob/elide-3.0-wip/elide-example/elide-blog-example/src/main/java/com/yahoo/elide/example/Main.java#L29) in our example, we are using embedded jetty and instructing it to mount a pre-canned [JsonApiEndpoint](https://github.com/yahoo/elide/blob/elide-3.0-wip/elide-core/src/main/java/com/yahoo/elide/resources/JsonApiEndpoint.java#L42) (which mounts to `/` by default) provided by Elide. You'll notice that the constructor takes two _named_ injection parameters (one for Elide and one for extracting a user for security purposes). Referring back to the example code, the Jersey [ResourceConfig](https://github.com/yahoo/elide/blob/elide-3.0-wip/elide-example/elide-blog-example/src/main/java/com/yahoo/elide/example/ElideResourceConfig.java#L33) binds both of these parameters so the resource can be created properly. In there you can see how an Elide instance is created. From there the endpoint uses that Elide instance to service requests. Moreover, this means that the _structure_ of the API is tied directly to your data model (though things can be renamed and `@Include`, `@Exclude`'d or secured with the `@ReadPermission`, etc. annotations as necessary). I'm not sure I exactly answered your question here, so please let me know if something is still unclear :)

3. Short answer: Yes it works. However, Elide itself does not support OPTIONS requests since it is just a middleware. As long as you're using a webserver technology that supports OPTIONS properly you should see no problems (i.e. jetty or similar). We do have real world experience with this however, and can confirm that this works just fine. We have production services that require this ability to behave and have no problems using CORS with Elide.

**Comment by DeathByTape** [comment]
@MikeSuiter does this answer your questions?

**Comment by MikeSuiter** [comment]
Yes that does for now and I'll check out 3.0 when it comes out. Thx.

**Comment by clayreimann** [comment]
3.0 is out! 🎉

**Comment by DeathByTape** [comment]
Great, thanks; closing this issue for now. Please feel free to reopen if you have any more issues!
