### ISSUE TITLE
Problems when pagination with "@ReadPermission" on entity

### ISSUE THREAD

**Issue by edgarmartins** [yahoo/elide#562]
This entity has more than 10,000 records.

ENTITY
=====
```
@ReadPermission(expression = "readCheck")
@Entity
@Table(name = "resource")
@NamedQuery(name = "Resource.findAll", query = "SELECT r FROM Resource r")
//@Paginate(countable = true, maxLimit = 100, defaultLimit = 50)
@Include(rootLevel = true, type = "resources")
public class Resource {
```

SEARCH
======
1. Error: "InvalidPredicateException: Cannot paginate resources"
http://localhost:8081/resources?filter[resources.description][infix]=table&sort=description&page[totals]

2. Error: "InvalidPredicateException: Cannot paginate resources"
http://localhost:8081/resources?filter[resources.description][infix]=table&sort=description&page[size]=10&page[number]=1

3. Error: "InvalidPredicateException: Cannot paginate resources"
http://localhost:8081/resources?filter[resources.description][prefix]=table&sort=description&page[size]=10&page[number]=1

WORKAROUND?
===========

Thanks!!!

**Comment by aklish** [comment]
What type of check is readCheck?

**Comment by aklish** [comment]
This is what is likely happening (without seeing your check implementation):

Your "readCheck" is attempting to perform a filter on the resources
collection in memory on your service.  The filter predicate you passed as a
query parameter is being pushed down to the database.
Pagination is implemented in the database.  Therefore, you can't apply an
in memory filter in your service after the collection has already been
filtered and paginated.

The fix for this is to implement readCheck as a FilterExpressionCheck.  In
this way, both your security filter and your query parameter filter are
executed in a single place (in the database) and you can then
paginate correctly.

Alternatively, if you can express readCheck as a property of the
principal/user and not the data (implement a UserCheck), this will also
solve the problem.

Aaron

**Comment by edgarmartins** [comment]
Hi Aaron,

Thanks for your answer.

The logic is this: 
- I implemented an abstract class DefaultCheck that extends InlineCheck.
- The CRUD operations extend this class.

The problem is:
When I use @ReadPermission(expression = "readCheck"), the component ElideConfig defines the class that implements the text of parameter from annotation @ReadPermission.


DEFAULT_CHECK
```
public abstract class DefaultCheck<T> extends InlineCheck<T> {
	public boolean ok(T object, RequestScope requestScope, Optional<ChangeSpec> changeSpec, String methodRoles) {
                // ... logic code of this
		return true;
	}

	@Override
	public boolean ok(User user) {
		return false;
	}
}
```

READ_CHECK
```
public class ReadCheck<T> extends DefaultCheck<T> {
	@Override
	public boolean ok(T object, RequestScope requestScope, Optional<ChangeSpec> changeSpec) {
		return ok(object, requestScope, changeSpec, "readRoles");
	}
}
```

ELIDE_CONFIG
```
@Component
public class ElideConfig {

	@Autowired
	private EntityManagerFactory entityManagerFactory;

	@Bean
	@Named("elide")
	public Elide configureElide() {

		final AuditLogger auditLogger = new Slf4jLogger();
		final SessionFactory sessionFactory = entityManagerFactory.unwrap(SessionFactory.class);
		final DataStore dataStore = new HibernateStore.Builder(sessionFactory).build();

		Map<String, Class<? extends Check>> checks = new HashMap<>();
		checks.put("readCheck", ReadCheck.class);
		checks.put("createCheck", CreateCheck.class);
		checks.put("updateCheck", UpdateCheck.class);
		checks.put("deleteCheck", DeleteCheck.class);
		checks.put("shareCheck", ShareCheck.class);
		EntityDictionary entityDictionary = new EntityDictionary(checks);

		return new Elide(new ElideSettingsBuilder(dataStore).withAuditLogger(auditLogger)
				.withEntityDictionary(entityDictionary).build());
	}
}
```

**Comment by aklish** [comment]
Hi,

If your logic is really to just allow access (return true), make it a
UserCheck instead.

That should solve the problem.  My prior analysis of your issue was correct.

Elide has different kinds of checks depending on what objects you need to
examine to evaluate your check.

If you need to just look at the user/principal executing the query or no
data at all, use a UserCheck.
UserChecks will only evaluate once per request and have no bearing on
pagination.

If you need to examine data that is stored in your DataStore, you should
try to use a FilterExpressionCheck for ReadPermissions.
The resulting FIlterExpression will be combined with the query parameter
filter to build
a singular SQL WHERE clause like:

WHERE <Security Filter Expression> AND <Query Parameter Filter Expression>

It is also more performant than running checks inside your middle tier.

The security docs should explain the difference.  Some of the tests have
some trivial examples.   In production, nearly all of our checks are either
UserChecks or FilterExpressionChecks
with an occasional InlineCheck for Deletes or Updates.

Let me know if this makes sense.

Aaron

**Comment by edgarmartins** [comment]
No Aaron,

I need more. I need to control all entities. The CRUD operations of this. I need to control, for example, if the user can update the entity. Or if the user can only select this entity.

Thanks!

**Comment by DennisMcWherter** [comment]
Sorry, I'm having a bit of trouble following your recent response; it seems to me there are a few questions in there.

**Controlling CRUD operations on entities.** CRUD operations are handled separately via the `@ReadPermission`, `@CreatePermission`, `@UpdatePermission`, `@DeletePermission`, and `@DeletePermission`. Depending on what you're trying to do, there is a tight-coupling in Elide 3 between `@CreatePermission` and `@UpdatePermission`. This coupling will be removed in Elide 4 (optimistically slated for release later this month) making all of these options distinct.

**Sharing one set of default permissions across entities.** Assuming these entities share a common package, you can annotate at the _package level_ by adding the permissions to your [package-info.java](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#packagecomment) for that package. This way you can annotate all of your entities one time for the whole package. Where there are exceptions, you can simply override on the specific entity at the entity- or field-level. I can give a more in-depth example if you have questions about this.

**Paginating large collections.** The pagination rules are unrelated to _collection size_. They are directly related to your permissions on a given model, however. What Aaron was saying above is that `InlineChecks` (for `@ReadPermission`) are fundamentally non-pageable. If you want your collection to support pagination, **all** of your `@ReadPermission` checks on **that entity** must be of type `UserCheck` or `FilterExpressionCheck`. The reason for this is `InlineChecks` and `CommitChecks` must be evaluated in-memory and _potentially_ depend on data from the actual objects themselves. As a result, to paginate your collection of 10,000 records, Elide would have to load all of the data for a particular entity type and then filter entirely in memory (to get the correct record count). Anyway, a quick break-down of when to use specific checks:

  * **UserCheck.** Use this check when your permission check is only concerned with some in-memory objects. This could be a user principal (i.e. provided via a trusted, signed, token for instance or retrieved out-of-band) or some other data source. Pagination works here since the checks are entirely ignorant of any entities being queried.
  * **FilterExpressionCheck.** This type of check is often really only applicable for retrieving data; they are pushed down directly to the datastore when queries are made. When your checks depend on the data for which you're trying to secure and you want to operate and this data collection is large enough to where performance or pagination are a concern. For instance, suppose I have a `Post` model with two fields: `status` and `owner`. I can use a `FilterExpressionCheck` to fetch all of the `draft` status posts with an `owner` matching my user principal's id. As previously mentioned, this check will be pushed down to the datastore directly. As a result, since this security is part of your query, we can accurately paginate the query since the datastore will provide accurate values to us with all of our filters.
  * **InlineCheck.** Use this check when you care about the data of the entity being accessed and you want to check it immediately upon access.
  * **CommitCheck.** This is similar to an InlineCheck except it will be deferred until the very end of your operation. Namely, if you're modifying an object and your check is only valid for a _fully updated object_, this is the type of check you would be interested in. However, `CommitCheck`s can be over-permissive if you're not careful. As a basic rule of thumb, `CommitCheck`s shouldn't really be used in `UpdatePermission`s unless you know why you're doing it. Consider a security check that depends on the `owner` field of an entity. If the update permission for the `owner` field is a `CommitCheck` that only allows the owner to make modifications, anyone can freely change the object's value to their own id and make changes as they wish (since at commit time, the new owner id value matches their id).

I hope this is clear.

It seems as though removing the `@ReadPermission` on your large collection fixes the pagination issue? If this is the case, it's certainly related to your check type. You're probably still extending `InlineCheck` instead of `UserCheck` or `FilterExpressionCheck`.

If you find that this won't easily work for you, please provide us with a small example of your code's logic that makes it difficult to convert from an `InlineCheck` to one of the others. We would be happy to help you through it (it looks like you omitted the check's logic entirely?). We don't need the exact check logic, but a representative example to better understand the issue you're encountering.

**Comment by edgarmartins** [comment]
Hi Dennis,

I understand.

Thanks.

Ed

**Comment by DennisMcWherter** [comment]
Glad to hear this helped! Feel free to ask if you have any other questions.

Also, we will be rewriting our docs very soon (in anticipation of Elide 4.0) so we'll make sure to get all this information captured clearly there too so it's more easily searchable.
