### ISSUE TITLE
Can't use @Id on private field

### ISSUE THREAD

**Issue by jstemen** [yahoo/elide#644]
I've noticed when I try to annotate a field with @id, Elide isn't able to find it.  Is this intentional?  It seems like Elide should scan both public and private fields when looking for id annotations.

I haven't tracked down the issue entirely, but I believe part of this behavior is because of this line:

https://github.com/yahoo/elide/blob/dc214abddde61de80e4f56ceb2ec9651f5a878df/elide-core/src/main/java/com/yahoo/elide/core/EntityBinding.java#L119

The line should be like this instead:
`        fieldOrMethodList.addAll(Arrays.asList(cls.getDeclaredFields())`

getFields() only returns public fields.  getDeclaredFields() returns public and private fields.

**Comment by aklish** [comment]
It is not intentional.  Elide supports JPA annotations on properties.  In theory, there is no reason it couldn't also support annotations on fields.  However, there are no tests for this. 

Properties over fields is just a legacy aspect of the models we use in production.  We would fully support a PR to support field level access as well.

Most of this work however would be augmenting the tests to make sure everything was covered.  I suspect the non-test code would be minimal.

**Comment by Mishanya840** [comment]
+++

**Comment by aklish** [comment]
High priority issue.  We should plan on fixing in the next month or so.
