### ISSUE TITLE
Hibernate 5.2. issue: org.hibernate.SessionFactory.getAllClassMetadata is no longer supported

### ISSUE THREAD

**Issue by Brutus5000** [yahoo/elide#660]
Hi there,

while migrating to Hibernate 5.2 I ran into the exception above.

Even though the code has been changed in the AbstractHibernateStore here https://github.com/yahoo/elide/commit/db57a0d7bfb7f1acc2a355edc01c66e7457ba6f0#diff-6738c8055c9f9da24bec18c11ef0b6f8L104 , the `HibernateEntityManagerStore` still overrides `populateEntityDictionary` with the original implementation and uses the unsupported `org.hibernate.SessionFactory.getAllClassMetadata`.

Does the `HibernateEntityManagerStore` require a different implementation or is this just leftovers?

**Comment by DennisMcWherter** [comment]
@klish did you work on this? Changing minor versions of hibernate5 has been a painful process for us. I know rather than deprecating and leaving functionality in place (or just removing the method so it fails at compile time), it throws a runtime exception which is unfortunate since this comes up at runtime.

Are you using the latest version of Elide as well?

**Comment by aklish** [comment]
I think this is a pretty simple fix.  Good catch @Brutus5000.  I'll submit a small PR.
