### ISSUE TITLE
Support RSQL INFIX, POSTFIX, and PREFIX filters on number types.

### ISSUE THREAD

**Issue by aklish** [yahoo/elide#800]
Elide currently can't support filters like:
`filter[books]=id==*20*`

It will return 
`{"errors":["InvalidValueException: Invalid value: “*20*"]}`

Inside RSQLFilterDialect, Elide attempts to type coerce the arguments of the predicate to the correct type:

```Java
            //Coerce arguments to their correct types
            List<Object> values = arguments.stream()
                    .map((argument) -> (Object) CoerceUtil.coerce(argument, relationshipType))
                    .collect(Collectors.toList());
```
The type coercion logic is happening too soon.  We should first strip off any asterisk characters (depending on the operator).

**Comment by QubitPi** [comment]
@aklish Stripping off any asterisk reminds me about other regex characters. Asterisk can be generalized to any character in a valid regex expression. If we agree on that, here is my strategy for fixing this issue:

I assume there is absolutely no way to coerce `*20*` to a `long` type. If we could treat `*20*` a regex, we will coerce `*20*` to `String` instead of `Long`.

Implementation-wise, we will check if `argument` is a regex string, if it is, override `relationshipType` to `String`

**Comment by clayreimann** [comment]
I disagree. If the id type here is numeric then `*20*` is not a valid filter. If Id is a string type then I don’t see why this wouldn’t work. 

Are you proposing that instead we should allow `=id==*20*` to match ids like `200` and `320`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aklish** [comment]
The asterisk character is part of the RSQL grammar.  When the RSQLFilterDialect finds tokens like '*20*', it should remove the asterisks before extracting the value (20 in this case).  We don't need any type coercion.   We just need some special logic inside RSQLFilterDialect to handle asterisk correctly.   Does this make sense?
