### ISSUE TITLE
Spring Integration

### ISSUE THREAD

**Issue by jackmatt2** [yahoo/elide#86]
Does this play nicely with spring framework?  Is there a sample project somewhere using spring?

**Comment by DeathByTape** [comment]
Great question. We have not made any concerted efforts for Spring interop and I'm not sure if anyone has tried at this point. If you are noticing issues, it would be great to see what they are.

By and large, I do not see a fundamental issue in using the Spring framework in conjunction with Elide unless you plan on using Spring REST on the same data model objects (i.e. your servlet layer may end up fighting). From other experiences, however, you could setup distinct endpoints where one is controlled by Elide and others are controlled by whatever other bits you care about.

Can you provide a small example of which Spring packages you're looking to use? I would be happy to briefly explore this. We're also improving our documentation, so if this would be useful we can add an example there as well.

Just let us know!

**Comment by jackmatt2** [comment]
I will be using [http://projects.spring.io/spring-boot/](spring-boot) including [spring-data-jpa](http://projects.spring.io/spring-data-jpa/) and spring-web-mvc.  I am a little concerned about all the business logic being set in the entity itself as this is a not a spring managed bean, rather, a jpa managed object.  It would make it difficult to @Inject the email service into the entity directly.

**Comment by DeathByTape** [comment]
Sorry for the delay here; we've been pretty heads down on hardening and features. That said, it looks like Matt Casperson helped us out here and published some integration articles about this on DZone :+1: 

See the issue here for the links: https://github.com/yahoo/elide/issues/193

**Comment by lorenzleutgeb** [comment]
I checked #193 and the articles mentioned there. However, I think that the point @jackmatt2 raised is not addressed in any of them. The question how to deal with business logic being moved/tied to the data model is not answered.

In the README for `elite-standalone` you state:
> While Elide is typically a pluggable middleware framework, we have constructed a flexible and complete service to allow you to get started quickly.

Many Spring projects are structured in a Three-Tier/Layer architecture, with the layers being Presentation (contains controllers), Application (also "Business", contains services), Persistence (contains repositories and data model). In this context, a "middleware" would affect the Presentation layer, effectively translating GraphQL/JSONAPI requests coming in via HTTP into requests that the Application layer or a thin wrapper before the Application layer can consume.
This view is not compatible with annotating the data model, as is suggested by the articles posted.

With Elide it is currently very easy to get a GraphQL/JSONAPI webservice up and running. Neat features like checks and hooks are available. But the downside is that they are tied to persistence. This stresses the Application layer in between. For example, @jackmatt2 hints that the business logic he is working on involves sending e-mails. This cannot be achieved without some really horrible workarounds.

Elide should allow for a mode of operation where it does not go all the way down to the data store, but presents the request it is trying to answer to the Application layer. This way, one could call other services to handle more involved business logic and also persistence.

**Comment by aklish** [comment]
A few thoughts and caveats.  First, I don't use Spring - so I can't comment directly on how Elide might best fit within that framework.
 
That said, there are two undergirding philosophies to Elide (and one key assumption):
 
1. Elide exposes a relational data model as a service.  Security and business logic are tied to that model.
It was our belief that this is the most flexible way to support a variety of applications with the minimal service layer footprint.
Rather than define our own annotations for describing the relationships between entities - we leveraged JPA for this purpose.
 
2. While JPA implies persistence, it really doesn't have to with Elide.  Elide has a `DataStore` abstraction - where the presentation
data model can be mapped (with traditional DAOs or other means) to the underlying persistence layer.  Elide can work with multiple
different data stores (one per entity) so in theory can stitch things together across them.  We do this quite a bit in our own production systems.

Here is the key assumption though:

We have found that our presentation model and persistence model are so similar in the bulk of scenarios that there is
no requirement to separate them.  Elide makes the common case simple (another reason we chose to use JPA rather than invent 
our own annotations for the same purpose).

In our system, we have entities that map to functional logic, to multiple physical tables, to reduced views of the physical tables, and to different kinds
of persistence layers.  Elide was not intended to merge persistence with presentation.   I agree that it is desirable to separate these concepts
in many instances.

Anyway, if you have thoughts on a better way to do this while at the same time preserving the simplicity of the common case, we would be open to exploring
the options.

Hope this is helpful.

**Comment by aklish** [comment]
I agree we probably need some documentation here.

I did a cursory look at crnk, but I honestly don't see much of a difference.  Crnk has the following docs:

```9.1.8. Customizing the exposed resources over the underlying entity model
Not always it is desired to have a 1:1 mapping between resources and entities. There are various techniques to customize the resource model:

Make use of the Crnk and Jackson annotations like @JsonApiResource, JsonApiRelationId, JsonApiRelation and @JsonIgnore to modify the entities on the resource layer.

Setup a DB view matching the desired resource and declare it as entity. This typically is the most efficient way to implement complex entity/resource mappings.

Setup a DTO mapping to map entities to resource objects (see the subsequent section for more information)```

1. The first suggestion is identical to `@Exclude`, `@Transient`, `@Computed...`
2. The second suggestion of using a view (for reads) with persistence hooks (for writes) on save is how we do the vast majority of our models that are quite different from the persistence layer.
3. The DTO mapping sounds similar to our DataSource - in that custom code does the mapping.  Maybe I'm missing something here.

I think Option 2 is something that really ought to be documented with an example.  It is really powerful.  You let the DB define the view.  With JPA annotations on the view entity, all the filters, sorting, pagination just work.  However, having the JPA annotations on the view entity are part of the reason this is so simple to make work.

Anyway, if you have a suggestion on a better way to map models or explain things in the docs better - I'd love to hear them.

**Comment by lorenzleutgeb** [comment]
crnk distinguishes Resources (one the JSONAPI side) from Entities. Conceptually, Resources are derived from Entities (see [`JpaEntityRepository`](https://github.com/crnk-project/crnk-framework/blob/master/crnk-jpa/src/main/java/io/crnk/jpa/JpaEntityRepository.java)), and you can decide how much to interfere. This translation can be influenced as suggested in (1.). However, regarding your response to (3.), crnk is more flexible. It is possible to map between these two representations independently of any persistence concerns. You suggest to implement such a customized mapper as part of a "data store", which draws a lot of attention to persistence.

I do not see this distinction in Elide, and think it would be quite helpful.

One question that would help me to understand your view: What is the Elide counterpart to [repository decoration](http://www.crnk.io/releases/stable/documentation/#_repository_decoration) or just overriding [`ResourceRepositoryBase`](https://github.com/crnk-project/crnk-framework/blob/master/crnk-core/src/main/java/io/crnk/core/repository/ResourceRepositoryBase.java)?
