### ISSUE TITLE
Introducing Business Logic

### ISSUE THREAD

**Issue by jackmatt2** [yahoo/elide#87]
From the documentation I can't see how you can customise operations.  For example, when a user is created, maybe an email is sent to the manager and another message is sent to a legacy system via JMS.  Is this sort of thing supported or in the pipeline?

**Comment by DeathByTape** [comment]
We have good news and bad news. The bad news, is that we didn't go into sufficient detail on this in the docs and that's why you couldn't find it! :-1: 

The good news: we do support this! :+1: If you look in the [lifecycle events section](http://elide.io/pages/guide/05-extension.html) of the docs, you'll notice that we briefly touch upon `@OnCommit` and `@OnUpdate` annotations. We actually support this for all operations, in fact. That is, there is an equivalent `@OnCreate`. We **do not** support an `@OnRead` since you already have control of the getter method for that :)

I will look into updating the docs today to make this clearer. Thank you for calling this out!

Please verify that this addresses your question and we can close the issue!
